[extend]
useDefault = true

[allowlist]
description = "global allow lists"
paths = [
    '''gitleaks.toml''',
    '''venv''',
]

[[rules]]
    id = "Hardcoded credentials"
	description = "Hardcoded credentials"
	regex = '''(?i)(?:secret|key|signature|password|pwd|pass|token)(?:\w|\s*?)(?:=|:=)(?:\s*?)[\"'`](.{1,120}?)[\"'`]'''
    secretGroup = 1


[[rules]]
    id = "Url capture" 
    description = "Credentials in url"
    regex = '''\b(?:http|https|ftp|ftps|sftp):\/\/[^:]+:([^@]+)@'''
    secretGroup = 1